# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=100)),
                ('tax_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTaxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.IntegerField()),
                ('total_deductions', models.IntegerField()),
                ('userbio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserBio')),
            ],
        ),
    ]
